### ISSUE TITLE
node sonus.js

### ISSUE THREAD

**Issue by jisu-1111** [evancohen/sonus#82]
$ npm run sonus

> smart-mirror@0.0.17 sonus /home/pi/test-smart-mirror/smart-mirror
> node sonus.js

module.js:549
    throw err;
    ^

Error: Cannot find module '/home/pi/test-smart-mirror/smart-mirror/node_modules/snowboy/lib/node/binding/Release/node-v57-linux-arm/snowboy.node'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/test-smart-mirror/smart-mirror/node_modules/snowboy/lib/node/index.js:8:29)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! smart-mirror@0.0.17 sonus: `node sonus.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the smart-mirror@0.0.17 sonus script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-04-25T08_11_43_432Z-debug.log

what's problem?
node is latest version 8.xx and npm version is 5.6.0
please , help me

**Comment by evancohen** [comment]
This looks like a smart mirror related issue - I'd recommend that you try reinstalling snowboy from within your `test-smart-mirror` directory. 

```
npm rm snowboy
npm install snowboy
```

**Comment by jisu-1111** [comment]
Thank you for your reply.But there was another problem.
How can i fix it?

Error: libcblas.so.3: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/test-smart-mirror/smart-mirror/node_modules/snowboy/lib/node/index.js:8:29)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! smart-mirror@0.0.17 sonus: `node sonus.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the smart-mirror@0.0.17 sonus script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-05-02T08_38_45_837Z-debug.log

**Comment by evancohen** [comment]
Looks like you're missing the native dependencies. Double check that you have them all installed

**Comment by jisu-1111** [comment]
Thank you for your reply.But there was another problem.
How can i fix it? help me plz


npm run sonus

> smart-mirror@0.0.17 sonus /home/pi/smart-mirror
> node sonus.js

!
!h: 1

!f: 
!e: { streamingError: 
   { Error: 3 INVALID_ARGUMENT: Invalid recognition 'config': bad language code.
    at Object.exports.createStatusError (/home/pi/smart-mirror/node_modules/grpc/src/common.js:87:15)
    at ClientDuplexStream._emitStatusIfDone (/home/pi/smart-mirror/node_modules/grpc/src/client.js:235:26)
    at ClientDuplexStream._readsDone (/home/pi/smart-mirror/node_modules/grpc/src/client.js:201:8)
    at /home/pi/smart-mirror/node_modules/grpc/src/client_interceptors.js:720:15
     code: 3,
     metadata: Metadata { _internal_repr: [Object] },
     details: 'Invalid recognition \'config\': bad language code.' } }

**Comment by evancohen** [comment]
What's the language code (eg: `en-US`) you are using in your smart mirror config? Make sure what you are using is supported.
